openapi: 3.0.1
info:
  title: Storeclaims
  version: 0.1.0
servers:
- url: "{server}:{port}/storeclaims"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /:
    post:
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimIdData'
      responses:
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "201":
          description: Created
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    ClaimIdData:
      required:
      - claimId
      type: object
      properties:
        claimId:
          type: string
