### Local Insurance Claims API calls without security
@claimIDLocal = 

###
curl -X POST 
http://localhost:3000/api/claims 
-H "Content-Type: application/json" 
-d '{"customerId": "cust123", "policyId": "pol123", "amount": 5000, "description": "Accident damage"}'

###
curl 
http://localhost:3000/api/claims/{{claimIDLocal}}


###
curl -X PUT 
http://localhost:3000/api/claims/{{claimIDLocal}}/status 
-H "Content-Type: application/json" 
-d '{"status": "approved"}'


###
curl 
http://localhost:3000/api/customers/cust123/claims


###
curl -X POST 
http://localhost:3000/api/claims/{{claimIDLocal}}/notify


###
curl -X POST http://localhost:8080/storeclaims -H "Content-Type: application/json" -d '{"claimId": @{{claimIDLocal}}}'






### Expose localhost API on Internet so we can create "API Proxy" in Choreo and use security
ssh -R 80:localhost:3000 nokey@localhost.run

### Use the API endpoint like the below, remember to append `api/`
https://cbce32909e666b.lhr.life/api/






### Choreo Insurance Claims API Call with security
@token = 
@claimIDChoreo = 

###
curl -X POST 
https://b48cc93e-fa33-4420-a155-bc653b4d46be-dev.e1-us-east-azure.choreoapis.dev/brkz/insuranceclaims/v1.0/claims \
-H "Content-Type: application/json" \
-H "Authorization: Bearer {{token}}" \
-d '{"customerId": "cust123", "policyId": "pol123", "amount": 5000, "description": "Accident damage"}'


###
curl 
https://b48cc93e-fa33-4420-a155-bc653b4d46be-dev.e1-us-east-azure.choreoapis.dev/brkz/insuranceclaims/v1.0/claims/{{claimIDChoreo}} \
-H "Authorization: Bearer {{token}}"


###
curl -X PUT 
https://b48cc93e-fa33-4420-a155-bc653b4d46be-dev.e1-us-east-azure.choreoapis.dev/brkz/insuranceclaims/v1.0/claims/{{claimIDChoreo}}/status \
-H "Authorization: Bearer {{token}}" \
-H "Content-Type: application/json" \
-d '{"status": "approved"}'







### Asgardeo call to get access token manually
@asgardeoCode = 

### Have to put this on browswer address bar and login and get the "code" (asgardeoCode)
https://api.asgardeo.io/t/viggnah/oauth2/authorize?response_type=code&client_id=kijZfyncfVZsNtYR6vt4aHFM3osa&redirect_uri=https://localhost:5000&scope=email,openid,profile,groups,roles,app_roles,submit-claims,read-claims

###
curl https://api.asgardeo.io/t/viggnah/oauth2/token \
 -d grant_type=authorization_code \
 -d client_id=kijZfyncfVZsNtYR6vt4aHFM3osa \
 -d redirect_uri=https://localhost:5000  \
 -d code={{asgardeoCode}}
